name: Build with make

on:
  push:
    branches: [ master, ci-run-test ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix:
        os: [ubuntu-latest]
        compiler: [gcc]    

    env: PATH=$PATH:$(pwd)/fribidi/c2man/c2man-install
    steps:
    - run: PATH=$PATH:$(pwd)/fribidi/c2man/c2man-install
    - uses: actions/checkout@v2
    - name: build c2man
      run: bash .ci/build-c2man.sh
    - name: configure
      run: ./autogen.sh
    - run: make
    - run: make check
    - run: make distcheck