name: Build with meson

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-gcc:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install meson ninja
    # TODO: fix c2man build
    # - name: build c2man
    #   run: bash .ci/build-c2man.sh
    - name: configure
      run: meson build -Ddocs=false
    - name: ninja build
      run: ninja -C build
    - name: ninja test
      run: ninja -C build test

  build-msvc:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Set up meson
      run: |
        python -m pip install --upgrade pip
        pip install meson ninja
    # TODO: fix docs build
    - name: configure
      run: meson build -Ddocs=false
    - name: ninja build
      run: ninja -C build
    - name: ninja test
      run: ninja -C build test
